### ISSUE TITLE
Inferno tricks

### ISSUE THREAD

**Issue by dfrese** [localvoid/uibench#7]
It seems to me, that inferno is doing some invalid 'optimizations' in its uibench implementation.
Looking at https://infernojs.github.io/uibench-inferno/docs/1.0/index.html?report=false&i=10&filter=table/[100,4]/render  shows, that all but the first render get down 0.
Looking at the code, it's probably the comparison with "lastData" and the NO_OP.

I would think that the 'iterations' are there to stabilize the measured timings, and not to measure 'no change' rendering.

If both is true, those wrong implementations of the benchmark should be checked.
If not, I apologize to the inferno people ;-)

**Comment by localvoid** [comment]
Code with `NO_OP` operations is just the way it implements `sCU` optimization for functional components. But I agree, this is an ugly way to do this, and nobody will do such things in real apps :)

It has such fast render times because of recycling. On 2nd interation it will just take prerendered table and insert it back. There is a flag in results section that indicates when library is using recycling. I can't block any implementations with such "optimizations" because Imba library doesn't work in any other way, its syncing algorithm is hugely depends on such behaviour.

**Comment by dfrese** [comment]
Ok, thanks for the explanations!

**Comment by localvoid** [comment]
Added Inferno implementation without any tricks, not so impressive anymore.

**Comment by leeoniya** [comment]
@localvoid can you provide any implementation guidelines for UIBench? what is and isnt acceptable? for example, i see there are click handlers bound in every td. Is this done specifically to stress test the libs or something that's needed to address some specific lib's limitations that can't do delegation cleanly (similar to the Imba sCU limitation above)? node recycling is also a fundamental thing provided by vdom libs, so i dont know what point there is to have both versions in the same comparison table. same goes for by-key tracking.

A domvm user stumbled upon UI bench and did a sub-optimal implementation [1] and I'm not sure what to tell him since I don't know what you'd consider "useless tricks" :) but would like to submit a fair version here.

[1] https://github.com/leeoniya/domvm/issues/104#issuecomment-264540591

**Comment by localvoid** [comment]
If you have implementation that is comptatible with React API, I think that it should be at least look like it is implemented in React. I am sorry for the comment that I've added below new Inferno implementation, I'll change it when I get home.

I am ok with any implementations, I'll accept any implementations :) Just be honest with the audience that you are trying to convince to use your library. Because you obviously understand that recycling has nothing to do with insert and render cases, and almost everyone who is using it, just want to show better results. kivi always had way more complicated recursive recycling that is able to capture whole dom subtrees in the pool, but what is the point to measure it, there is nothing to measure and optimize in recycling.
